env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

rules:
  react/sort-comp: [1, {
    order: [
      'lifecycle',
      '/^_.+$/',
      'everything-else',
      'render',
      'static-methods'
    ]
  }]

settings:
  react:
    version: '16'
